version: '3.8'

services:
  # แอปเทรดทองของเรา
  trading-app:
    build:
      context: ../my-trading-app  # ชี้ข้ามไปที่โฟลเดอร์ App
      dockerfile: Dockerfile
    container_name: my-trading-web
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/trading_db
    depends_on:
      - db

  # ฐานข้อมูล Postgres สำหรับเก็บประวัติการเทรด/จดหนี้
  db:
    image: postgres:15-alpine
    container_name: my-trading-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: trading_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
      # - "5432:5432"

volumes:
  postgres_data: