version: '3.8'

services:
# 1. ด่านหน้าจัดการ Domain และ SSL (HTTPS)
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - '80:80'    # HTTP ปกติ
      - '443:443'  # HTTPS (SSL)
      - '81:81'    # หน้า Admin สำหรับตั้งค่า (เปิดเลข IP:81)
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
      
  # แอปเทรดทองของเรา
  trading-app:
    image: ghcr.io/wp-wachi/my-trading-app:latest
    container_name: my-trading-web
    restart: always
    # ports:
    #   - "80:3000" # ปิดไว้ เพราะเราจะให้ nginx-proxy เป็นคนส่ง Traffic มาให้เอง
    expose:
      - "3000" # ให้บริการเฉพาะภายในเครือข่าย Docker
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/trading_db
    depends_on:
      - db

  # 3. ฐานข้อมูล Postgres
  db:
    image: postgres:15-alpine
    container_name: my-trading-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: trading_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
      # - "5432:5432"

volumes:
  postgres_data: